# No mostrar la línea nueva al principio
add_newline = false

# Un formato simple y limpio
format = "$directory$git_branch$git_status$character"

[directory]
style = "bold #000000"
truncation_length = 3
truncation_symbol = "…/"

[character]
success_symbol = "[❯](#000000 bold)"
error_symbol = "[❯](#666666 bold)"

[git_branch]
symbol = " "
style = "bright-black"
